export const initialTodos = [
  {
    _id: '1',
    title: 'Complete React project',
    description: 'Finish the task manager application with all features and ensure all components are working properly',
    completed: false,
    createdAt: new Date().toISOString(),
    list: 'Work',
    dueDate: '2024-07-30',
    tags: ['Important', 'In Progress'],
  },
  {
    _id: '2',
    title: 'Review code changes',
    description: 'Go through all the recent commits and review the code quality, check for any potential bugs',
    completed: true,
    createdAt: new Date().toISOString(),
    list: 'Personal',
    dueDate: '2024-07-25',
    tags: ['Important'],
  },
  {
    _id: '3',
    title: 'Update project documentation',
    description: 'Write comprehensive documentation for the project including setup instructions and API documentation',
    completed: false,
    createdAt: new Date().toISOString(),
    list: 'Work',
    dueDate: '2024-08-10',
    tags: ['Planning', 'Low Priority'],
  },
  {
    _id: '4',
    title: 'Team meeting preparation',
    description: 'Prepare agenda and materials for the weekly team sync meeting',
    completed: false,
    createdAt: new Date().toISOString(),
    list: 'Work',
    dueDate: '2024-07-29',
    tags: ['Important', 'Planning'],
  },
  {
    _id: '5',
    title: 'Deploy to production',
    description: 'Deploy the latest version to production environment and verify all services are running correctly',
    completed: true,
    createdAt: new Date().toISOString(),
    list: 'Work',
    dueDate: '2024-07-20',
    tags: ['Important'],
  },
  {
    _id: '6',
    title: 'Grocery shopping',
    description: 'Buy vegetables, fruits, milk, bread, and other household essentials',
    completed: false,
    createdAt: new Date().toISOString(),
    list: 'Shopping',
    dueDate: '2024-08-15',
    tags: ['Low Priority'],
  },
  {
    _id: '7',
    title: 'Schedule dentist appointment',
    description: 'Call and schedule a routine dental checkup for next month',
    completed: false,
    createdAt: new Date().toISOString(),
    list: 'Health',
    dueDate: '2024-08-16',
    tags: ['Important', 'Planning'],
  },
  {
    _id: '8',
    title: 'Write blog post about React hooks',
    description: 'Create a detailed blog post explaining React hooks with examples and best practices',
    completed: false,
    createdAt: new Date().toISOString(),
    list: 'Personal',
    dueDate: '2024-08-17',
    tags: ['Planning', 'Low Priority'],
  },
  {
    _id: '9',
    title: 'Optimize database queries',
    description: 'Review and optimize slow database queries to improve application performance',
    completed: false,
    createdAt: new Date().toISOString(),
    list: 'Work',
    dueDate: '2024-08-18',
    tags: ['Important', 'In Progress'],
  },
  {
    _id: '10',
    title: 'Plan weekend trip',
    description: 'Research destinations, book accommodations, and create itinerary for the weekend getaway',
    completed: false,
    createdAt: new Date().toISOString(),
    list: 'Travel',
    dueDate: '2024-08-19',
    tags: ['Planning'],
  },
  {
    _id: '11',
    title: 'Fix critical bug in payment module',
    description: 'Investigate and fix the payment processing issue reported by users',
    completed: true,
    createdAt: new Date().toISOString(),
    list: 'Work',
    dueDate: '2024-07-15',
    tags: ['Important'],
  },
  {
    _id: '12',
    title: 'Update resume and portfolio',
    description: 'Add recent projects and update skills section with latest technologies',
    completed: true,
    createdAt: new Date().toISOString(),
    list: 'Personal',
    dueDate: '2024-07-16',
    tags: ['Low Priority'],
  },
];
