module.exports = {
  LIST_ERRORS: {
    LIST_NOT_FOUND: "LIST_NOT_FOUND",
    LIST_EXISTS: "LIST_EXISTS",
    DEFAULT_LIST: "DEFAULT_LIST",
    UNAUTHORIZED: "UNAUTHORIZED",
    LIST_NAME_REQUIRED: "LIST_NAME_REQUIRED"
  },
  TAG_ERRORS: {
    TAG_NOT_FOUND: "TAG_NOT_FOUND",
    TAG_EXISTS: "TAG_EXISTS",
    DEFAULT_TAG: "DEFAULT_TAG",
    UNAUTHORIZED: "UNAUTHORIZED"
  },
  TODO_ERRORS: {
    TODO_NOT_FOUND: "TODO_NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED"
  },
  AUTH_ERRORS: {
    EMAIL_EXISTS: "EMAIL_EXISTS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_SESSION: "INVALID_SESSION",
  }
};